// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcY75q2qDs-umufYCRZB9Gk4W2DcVf_x0',
    appId: '1:923914389386:web:cbc356045c0ea17dcd6a73',
    messagingSenderId: '923914389386',
    projectId: 'smartcampusalertsystem',
    authDomain: 'smartcampusalertsystem.firebaseapp.com',
    storageBucket: 'smartcampusalertsystem.firebasestorage.app',
    measurementId: 'G-MHEV3FS1CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr6TBM_cJTLpAn4k8imxNFIwE-WGHFmfA',
    appId: '1:923914389386:android:a9b98a89d253b259cd6a73',
    messagingSenderId: '923914389386',
    projectId: 'smartcampusalertsystem',
    storageBucket: 'smartcampusalertsystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMI5wu3OxQGyEp3Wb7RGt7uW4N5JBvx2c',
    appId: '1:923914389386:ios:d5f2faaee14552ebcd6a73',
    messagingSenderId: '923914389386',
    projectId: 'smartcampusalertsystem',
    storageBucket: 'smartcampusalertsystem.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusAlertSystem',
  );
}
